import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Explicitly structuring the sidebar for better organization
  tutorialSidebar: [
    'intro', // The introduction page
    {
      type: 'category',
      label: '📖 Physical AI & Robotics',
      link: {
        type: 'generated-index',
        title: 'Physical AI & Robotics',
        description: 'The complete course text, divided into parts and chapters.',
        slug: '/category/physical-ai-and-robotics'
      },
      items: [{type: 'autogenerated', dirName: 'physical-ai-and-robotics'}],
    },
    {
      type: 'category',
      label: '📚 Course Outline',
      link: {
        type: 'generated-index',
        title: 'Course Outline',
        description: 'Syllabus, learning outcomes, and hardware requirements.',
        slug: '/category/course-outline'
      },
      items: [{type: 'autogenerated', dirName: 'course-outline'}],
    },
    {
      type: 'category',
      label: ' Docusaurus Tutorials',
      items: [{type: 'autogenerated', dirName: 'tutorial-basics'}, {type: 'autogenerated', dirName: 'tutorial-extras'}],
    },
  ],
};

export default sidebars;
